# Generated by Django 5.1.6 on 2025-02-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='数据值')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='标签名')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='类型')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('order_num', models.SmallIntegerField(blank=True, null=True, verbose_name='排序号')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注信息')),
                ('create_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人ID')),
                ('create_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人名称')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('modify_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='修改人ID')),
                ('modify_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='修改人名称')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '字典表',
                'verbose_name_plural': '字典表',
                'db_table': 'sys_dict',
            },
        ),
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.BigIntegerField(verbose_name='父级编号')),
                ('parent_ids', models.CharField(blank=True, max_length=2000, null=True, verbose_name='所有父级编号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单名称')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, max_length=200, null=True, verbose_name='组件路径')),
                ('permission', models.CharField(blank=True, max_length=200, null=True, verbose_name='权限标识')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单图标')),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, '目录'), (1, '菜单'), (2, '按钮')], null=True, verbose_name='菜单类型')),
                ('is_frame', models.SmallIntegerField(default=0, verbose_name='是否为外链')),
                ('order_num', models.SmallIntegerField(blank=True, null=True, verbose_name='排序号')),
                ('status', models.SmallIntegerField(default=1, verbose_name='菜单状态')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注信息')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '菜单表',
                'verbose_name_plural': '菜单表',
                'db_table': 'sys_menu',
            },
        ),
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='角色名称')),
                ('order_num', models.SmallIntegerField(blank=True, null=True, verbose_name='排序号')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注信息')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
                'db_table': 'sys_role',
            },
        ),
        migrations.CreateModel(
            name='SysRoleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.BigIntegerField(verbose_name='角色编号')),
                ('menu_id', models.BigIntegerField(verbose_name='菜单编号')),
            ],
            options={
                'verbose_name': '角色菜单表',
                'verbose_name_plural': '角色菜单表',
                'db_table': 'sys_role_menu',
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=32, null=True, verbose_name='密码')),
                ('salt', models.CharField(blank=True, max_length=20, null=True, verbose_name='盐')),
                ('nick_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户昵称')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机')),
                ('user_type', models.SmallIntegerField(blank=True, choices=[(1, '超级管理员'), (2, '普通用户')], null=True, verbose_name='用户类型')),
                ('photo', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户头像')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最近登录时间')),
                ('last_login_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='最近登录IP')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注信息')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建者')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'sys_user',
            },
        ),
        migrations.CreateModel(
            name='SysUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True, verbose_name='用户ID')),
                ('role_id', models.BigIntegerField(blank=True, null=True, verbose_name='角色ID')),
            ],
            options={
                'verbose_name': '用户角色表',
                'verbose_name_plural': '用户角色表',
                'db_table': 'sys_user_role',
            },
        ),
    ]
