# Generated by Django 5.1.6 on 2025-02-28 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='alarm_image')),
                ('original_image', models.ImageField(upload_to='original_image')),
                ('label_image', models.ImageField(upload_to='label_image')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('alarm_time', models.DateTimeField(auto_now_add=True)),
                ('alarm_type', models.CharField(max_length=32)),
                ('alarm_desc', models.CharField(max_length=32)),
                ('callback', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '报警图片',
                'verbose_name_plural': '报警图片',
                'db_table': 'alarm_image',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='数据集名称')),
                ('description', models.TextField(verbose_name='数据集描述')),
                ('path', models.CharField(max_length=255, verbose_name='存储路径')),
                ('type', models.CharField(max_length=32, verbose_name='数据集类型')),
                ('created_by', models.CharField(max_length=32, verbose_name='创建者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '数据集',
                'verbose_name_plural': '数据集',
                'db_table': 'dataset',
            },
        ),
        migrations.CreateModel(
            name='DetectionConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255, verbose_name='输入源路径')),
                ('conf', models.FloatField(default=0.25, verbose_name='置信度阈值')),
                ('iou', models.FloatField(default=0.7, verbose_name='IoU阈值')),
                ('half', models.BooleanField(default=False, verbose_name='使用半精度')),
                ('device', models.CharField(default='cuda', max_length=32, verbose_name='运行设备')),
                ('show', models.BooleanField(default=False, verbose_name='显示检测结果')),
                ('save', models.BooleanField(default=False, verbose_name='保存检测结果')),
                ('save_txt', models.BooleanField(default=False, verbose_name='保存为文本文件')),
                ('save_conf', models.BooleanField(default=False, verbose_name='保存置信度')),
                ('save_crop', models.BooleanField(default=False, verbose_name='保存裁剪图像')),
                ('hide_labels', models.BooleanField(default=False, verbose_name='隐藏标签')),
                ('hide_conf', models.BooleanField(default=False, verbose_name='隐藏置信度')),
                ('max_det', models.IntegerField(default=300, verbose_name='最大检测数')),
                ('vid_stride', models.IntegerField(blank=True, null=True, verbose_name='视频帧率步长')),
                ('line_width', models.IntegerField(blank=True, null=True, verbose_name='边界框线宽')),
                ('visualize', models.BooleanField(default=False, verbose_name='可视化特征')),
                ('augment', models.BooleanField(default=False, verbose_name='图像增强')),
                ('agnostic_nms', models.BooleanField(default=False, verbose_name='类别无关NMS')),
                ('retina_masks', models.BooleanField(default=False, verbose_name='高分辨率分割掩膜')),
                ('classes', models.CharField(blank=True, max_length=255, null=True, verbose_name='类别过滤')),
                ('boxes', models.BooleanField(default=True, verbose_name='显示边界框')),
            ],
            options={
                'verbose_name': '检测配置',
                'verbose_name_plural': '检测配置',
                'db_table': 'detection_config',
            },
        ),
        migrations.CreateModel(
            name='DetectionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=32)),
                ('model_path', models.CharField(max_length=255)),
                ('model_type', models.CharField(max_length=32)),
                ('model_desc', models.CharField(max_length=255)),
                ('model_version', models.CharField(max_length=32)),
                ('model_size', models.CharField(max_length=32)),
                ('user_id', models.CharField(max_length=32)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '识别模型',
                'verbose_name_plural': '识别模型',
                'db_table': 'detection_model',
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_id', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=32)),
                ('model_type', models.CharField(max_length=32)),
                ('model_desc', models.CharField(max_length=255)),
                ('model_version', models.CharField(max_length=32)),
                ('model_size', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='YoloTrainingConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_path', models.CharField(max_length=255, verbose_name='模型路径')),
                ('data_path', models.CharField(max_length=255, verbose_name='数据文件路径')),
                ('epochs', models.IntegerField(default=2, verbose_name='训练轮数')),
                ('image_size', models.IntegerField(default=320, verbose_name='训练图像尺寸')),
                ('batch_size', models.IntegerField(default=8, verbose_name='批次大小')),
                ('workers', models.IntegerField(default=0, verbose_name='工作线程数')),
                ('device', models.CharField(default='cuda', max_length=32, verbose_name='训练设备')),
                ('model_name', models.CharField(max_length=32, verbose_name='模型名称')),
                ('optimizer', models.CharField(default='SGD', max_length=32, verbose_name='优化器')),
                ('project', models.CharField(default='runs/train', max_length=32, verbose_name='项目路径')),
                ('name', models.CharField(max_length=32, verbose_name='训练名称')),
            ],
            options={
                'verbose_name': 'YOLO训练配置',
                'verbose_name_plural': 'YOLO训练配置',
                'db_table': 'yolo_training_config',
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detected_objects', models.JSONField(verbose_name='检测到的物体')),
                ('confidence', models.FloatField(verbose_name='总体置信度')),
                ('process_time', models.FloatField(verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotter.alarmimage', verbose_name='关联图片')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotter.detectionmodel', verbose_name='使用模型')),
            ],
            options={
                'verbose_name': '识别结果',
                'verbose_name_plural': '识别结果',
                'db_table': 'detection_result',
            },
        ),
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=32, verbose_name='任务状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_by', models.CharField(max_length=32, verbose_name='创建者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('log_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='日志路径')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotter.dataset', verbose_name='使用数据集')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotter.detectionmodel', verbose_name='关联模型')),
            ],
            options={
                'verbose_name': '训练任务',
                'verbose_name_plural': '训练任务',
                'db_table': 'training_task',
            },
        ),
    ]
