"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# 在项目中构建路径，如下所示: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# 安全警告：对生产中使用的密钥保密！
SECRET_KEY = 'django-insecure-yh#qtj)p8*2ai&=y)ctw$o9c9pl34dc5edl8h)q)jb2845v@%#'

# 安全警告：请勿在生产环境中开启调试的情况下运行！
DEBUG = True

ALLOWED_HOSTS = []

# 应用程序定义

INSTALLED_APPS = [  # Django 的自带应用
    'django.contrib.admin',  # 管理员站点
    'django.contrib.auth',  # 认证授权系统
    'django.contrib.contenttypes',  # 内容类型框架
    'django.contrib.sessions',  # 会话框架
    'django.contrib.messages',  # 消息框架
    'django.contrib.staticfiles',  # 管理静态文件的框架
    "spotter.apps.SpotterConfig", # 模型检测
    "appadmin.apps.AppadminConfig", # 管理员
]# settings.py

LOGGING = {
    'version': 1,  # 日志配置版本号
    'disable_existing_loggers': False,  # 是否禁用已存在的日志记录器

    # 日志格式定义
    'formatters': {
        'verbose': {  # 详细格式
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {  # 简单格式
            'format': '{levelname} {message}',
            'style': '{',
        },
    },

    # 日志处理器定义
    'handlers': {
        'file': {  # 文件处理器
            'level': 'INFO',  # 记录INFO级别及以上的日志
            'class': 'logging.FileHandler',  # 使用文件处理
            'filename': 'debug.log',  # 日志文件路径
            'formatter': 'verbose',  # 使用详细格式
        },
        'console': {  # 控制台处理器
            'level': 'DEBUG',  # 记录DEBUG级别及以上的日志
            'class': 'logging.StreamHandler',  # 使用控制台输出
            'formatter': 'verbose',  # 使用简单格式
        },
    },

    # 日志记录器配置
    'loggers': {
        'django': {  # Django框架日志
            'handlers': ['file', 'console'],  # 使用文件和控制台处理器
            'level': 'INFO',  # 记录INFO级别及以上的日志
            'propagate': True,  # 日志消息传递给父记录器
        },
        'backend.spotter': {  # spotter应用日志
            'handlers': ['file', 'console'],  # 使用文件和控制台处理器
            'level': 'DEBUG',  # 记录DEBUG级别及以上的日志
            'propagate': False,  # 日志消息不传递给父记录器
        },
    },
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# 数据库
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 指定数据库引擎mysql
        "NAME": "intelligent_home_monitor",
        "USER": "root",
        "PASSWORD": "1223769987",
        "HOST": "9.220.107.43",
        "PORT": "6306",
    }
}

# 密码验证
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 国际化进程
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'  # 设置时区为北京时间

USE_TZ = False  # 启用时区支持

USE_I18N = True

USE_L10N = True


# 静态文件（CSS、JavaScript、图像）
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# 默认主键字段类型
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
